package com.test.db;

import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.test.bean.UserBean;

public class DBServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Method stub generated by Lomboz
		process(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Method stub generated by Lomboz
		process(request, response);
	}

	protected void process(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Method stub generated by Lomboz
		try {
			Properties props = new Properties();
			String fileName = "C:\\CreateDB.properties";
			FileInputStream in = new FileInputStream(fileName);
			props.load(in);

			String drivers = props.getProperty("jdbc.drivers");
			if (null != drivers) {
				Class.forName(drivers);// 加载数据库驱动程序
			}
			String url = props.getProperty("jdbc.url");

			Connection con = DriverManager.getConnection(url);

			Statement stmt = con.createStatement();

			String sql = "select * from user";// 从user表中取得所有数据

			ResultSet rs = stmt.executeQuery(sql);

			List<Object> list = new ArrayList<Object>();

			UserBean bean = null;

			while (rs.next()) {
				bean = new UserBean();

				bean.setName(rs.getString("name"));
				bean.setPassword(rs.getString("password"));
				bean.setEmail(rs.getString("email"));
				bean.setWww(rs.getString("www"));
				bean.setTel(rs.getString("tel"));
				bean.setAddress(rs.getString("address"));
				bean.setPostcode(rs.getString("postcode"));

				list.add(bean);

			}
			rs.close();
			con.close();// 不要忘记关闭数据库连接

			request.setAttribute("list", list);

			request.getRequestDispatcher("/showDB.jsp").forward(request, response);
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}