##
## Build with appveyor
##
#
environment:
  matrix:
    # - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: java -version

platform:
  # - x86
  - x64

configuration:
  - Release

build_script:
  - mvn clean compile package install -B -Dmaven.test.skip=true