<%@ page contentType="text/html;charset=gb2312" pageEncoding="gb2312"%>
<html>
<head><title>test</title></head>
<body>
<%
	out.println("ÓÃ»§Ãû£º"+request.getParameter("User")+"<br>");
	out.println("ÃÜÂë£º"+request.getParameter("pwd")+"<br>");
	out.println("ä¯ÀÀÆ÷£º"+request.getParameter("radio")+"<br>");	
	out.println("±êÌâ£º"+request.getParameter("check1")+"<br>");
	out.println("ÏêÏ¸£º"+request.getParameter("check2")+"<br>");
	out.println("Òşº¬£º"+request.getParameter("hidden")+"<br>");
	out.println("getContentLength()="+request.getContentLength()+"<br>");	
	out.println("getContentType()="+request.getContentType()+"<br>");
	out.println("getRequestURI()="+request.getRequestURI()+"<br>");
	out.println("getServerPort()="+request.getServerPort()+"<br>");
	out.println("getServerName()="+request.getServerName()+"<br>");
	out.println("getProtocol()="+request.getProtocol()+"<br>");
	out.println("getRemoteAddr()="+request.getRemoteAddr()+"<br>");
	out.println("getHeaderNames()="+request.getHeaderNames()+"<br>");
	out.println("getMethod()="+request.getMethod()+"<br>");
	out.println("getServletPath()="+request.getServletPath()+"<br>");
	out.println("isRequestedSessionIdValid()="+request.isRequestedSessionIdValid()+
              "<br>");
%>
</body>
</html>
