package com.test.servlet;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.test.bean.Users;
import com.test.db.UsersDB;

public class ProcessUsersServlet extends HttpServlet
{

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException
	{
		// TODO Method stub generated by Lomboz
		process(request, response);
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException
	{
		// TODO Method stub generated by Lomboz
		process(request, response);
	}

	protected void process(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException
	{
		String type = request.getParameter("type");
		if ("save".equals(type))
		{
			String username = request.getParameter("username");
			String password = request.getParameter("password");
			String truename = request.getParameter("truename");
			String birthday = request.getParameter("birthday");
			String sex = request.getParameter("sex");
			String[] interest = request.getParameterValues("interest");
			String remark = request.getParameter("remark");

			java.sql.Date birthdayToDate = null;
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
			try
			{
				java.util.Date date = sdf.parse(birthday);
				birthdayToDate = new java.sql.Date(date.getTime());
			}
			catch (ParseException e)
			{

				e.printStackTrace();
			}
			String interestToString = null;
			StringBuffer sb = new StringBuffer();
			for (int i = 0; i < interest.length; i++)
			{
				sb.append(interest[i]);
			}
			interestToString = sb.toString();

			Users bean = new Users();
			bean.setUsername(username);
			bean.setPassword(password);
			bean.setTruename(truename);
			bean.setInterest(interestToString);
			bean.setSex(sex);
			bean.setBirthday(birthdayToDate);

			bean.setRegisterdate(new java.sql.Date(new java.util.Date()
					.getTime()));
			bean.setRemark(remark);
			UsersDB userDB = new UsersDB();
			userDB.save(bean);

			ArrayList arrayList = userDB.getAllUsers();
			request.setAttribute("all", arrayList);
			request.getRequestDispatcher("/listAllUsers.jsp").forward(
					request, response);

		}

		if ("remove".equals(type))
		{
			String id = request.getParameter("id");
			UsersDB userDB = new UsersDB();
			userDB.remove(Integer.parseInt(id));
			ArrayList arrayList = userDB.getAllUsers();
			request.setAttribute("all", arrayList);
			request.getRequestDispatcher("/listAllUsers.jsp").forward(
					request, response);

		}
	}

}