package test.test.filter;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;

public class UsersFilter implements Filter {

	public void init(FilterConfig config) throws ServletException {
		// TODO Method stub generated by Lomboz
	}

	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
			throws IOException, ServletException {
		// TODO Method stub generated by Lomboz
		((HttpServletRequest) request).setCharacterEncoding("gb2312");
		chain.doFilter(request, response);
	}

	public void destroy() {
		// TODO Method stub generated by Lomboz
	}

	public FilterConfig getFilterConfig() {
		// TODO Method stub generated by Lomboz
		return null;
	}

	public void setFilterConfig(FilterConfig config) {
		// TODO Method stub generated by Lomboz
	}
}