name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          mvn clean package

      - name: Rename WAR file
        run: |
          set -x
          CURRENT_DIR=$(pwd)
          TARGET_DIR="$CURRENT_DIR/java-web-test/target"
          ORIGINAL_WAR_FILE=$(ls -al java-web-test/target/java-web-test-*.war | awk '{print $9}')
          cp "$ORIGINAL_WAR_FILE" "java-web-test/target/java-web-test.war"

      - uses: actions/upload-artifact@v4
        with:
          name: java-web-test
          path: java-web-test/target/java-web-test.war

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: "124.222.145.48"
          username: "ubuntu"
          key: ${{ secrets.PRIVATE_KEY_FOR_DEPLOY }}
          port: 22
          source: "java-web-test/target/java-web-test.war"
          target: "/usr/local/tomcat/apache-tomcat-11.0.11/webapps/"
          timeout: 120s
      - name: Wait for Tomcat to start
        run: sleep 30
      - name: Test Home Page Accessibility
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://124.222.145.48:8080/java-web-test/index.jsp)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Test Home Page Accessibility failed, state code: $STATUS_CODE"
            exit 1
          fi
          echo "Test Home Page Accessibility successfully, state code: $STATUS_CODE"